### PR TITLE
Reorganize folder structure for Iris.

### PR DESCRIPTION
**Pull request by gogasca**
-Reorganize Iris directory for TF.
-Add Tensorflow folder.
-Add Tensorflow estimator example with TF 1.10.
-Move TF 1.2 example to deprecated folder.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/286)

### CODE REVIEW

**Comment by nnegrey** [comment]
Are these samples in the docs anywhere that also need to be updated?

**Comment by gogasca** [comment]
> Are these samples in the docs anywhere that also need to be updated?

Checking with Crystal

**Comment by gogasca** [comment]
@thedriftofwords Is there any docs linked to existing code that need to be updated? Thanks

**Comment by gogasca** [comment]
@nnegrey confirmed with @thedriftofwords no docs dependencies for Iris folder. Thanks

**Pull request merged**
