### PR TITLE
IMDB Keras example

### PR DESCRIPTION
**Pull request by gogasca**
**Dataset**: IMDB reviews.
**Goal**: Add Binary classification using Text embeddings. 
Created a Keras binary classifier based from Tensorflow.org [tutorial](https://www.tensorflow.org/tutorials/keras/basic_text_classification). 
This sample runs both as a standalone Keras code and on Cloud ML Engine.
This example classifies movie reviews as positive or negative using the text of
the review.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/256)

### CODE REVIEW

**Comment by gogasca** [comment]
Created https://github.com/GoogleCloudPlatform/cloudml-samples/issues/273

**Comment by dizcology** [comment]
Are the code files based on this notebook?  https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_text_classification.ipynb

Can we explore some automatic conversion tools that can reuse the code and the tutorial content itself?

**Comment by gogasca** [comment]
Hi Yu-Han, 
That is correct, all 3 PRs are based on those 3 tutorials. 
Are you thinking of re-using the existing Keras [Notebook](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/basic_text_classification.ipynb) into another Notebook for CMLE or convert the Keras Notebook into python code itself for CMLE ?

**Comment by nnegrey** [comment]
For our team creating samples, I don't think we need to create a SAMPLE_REQUEST form. 

My thoughts on the sample request form were for people to be able to make requests that they might not want to implement themselves or for people looking to contribute to the repo, they could go there and find stuff to work on and link them in the PR. Thoughts?

**Pull request merged**
