### PR TITLE
Update TPU samples.

### PR DESCRIPTION
**Pull request by 0olwzo0**
Remove the forked resnet TPU sample and add instruction to use samples from Cloud TPU.

### CODE REVIEW

**Comment by puneith** [comment]
@0olwzo0 So I looked at the TPU code in TF briefly and its using the Estimator API so looks like it will work well on Cloud ML Engine. And if that's the case then we should atleast show in the README how to run on Cloud ML Engine (while importing the actual code from TF)

**Comment by puneith** [comment]
Actually I see you are already doing that in this PR. Will take a detailed look.

**Comment by 0olwzo0** [comment]
Thanks!

**Comment by puneith** [comment]
LGTM

**Comment by 0olwzo0** [comment]
Thanks for reviewing! Merging now.

**Pull request merged**
