### PR TITLE
Use Exporter to save model

### PR DESCRIPTION
**Pull request by ohmystack**
## Signatures of exported model

If `tensorflow_model_server`(tensorflow/serving commit: `c2c68c21a`) serves a model without signatures, it will return an error when it handles a request.
```plain
AbortionError(code=StatusCode.NOT_FOUND, details="Missing signature ...
```
I don't know how `gcloud beta ml predict` works with this kind of model, which has no signatures, while `tensorflow_model_server` fails.
But sometimes, user wants to debug their saved model in `tensorflow_model_server` first.
As an example of CloudML, I would like to add signatures in it.

## Output model path

The `saver` writes the model directly under `model/`.
However, global_step is needed when using `exporter.Exporter` to export the model. The model directory name will be `model/<global_step>/`.

So, the output model path is different between using `saver` and `Exporter`.

Does the CloudML require the user program to save strictly under `model/`? (Cannot be `model/<global_step>/`?)

---

I know that CloudML team is not currently ready to accept contributions. I make this PR to discuss the issues above.

### CODE REVIEW

**Comment by joshgc** [comment]
I'm not an expert on CloudML serving, so I'll let others chime in on Saver vs Exporter.  

1) CloudML serving does require a signature (although it does not use that jargon).  The inputs and outputs get defined the same way as with an exporter.  See [here](https://cloud.google.com/ml/docs/how-tos/preparing-models) and look for "tf.add_to_collection".  The same Tensorflow call is used in several samples in this repo as well.

2) CloudML serving is agnostic to any directory structure or names so long as all the files it needs have the same path prefix ie ...

> gcloud beta ml versions create v1 --model flowers --origin gs://my_bucket/path/prefix/

**Comment by ohmystack** [comment]
Oh, I see. Thanks @joshgc . 
The "inputs/outputs" `collection` in CloudML has the same purpose as the `signature` in `tensorflow_model_server`.

Would CloudML team consider the compatibility of the saved model for both CloudML and tensorflow_model_server in the future? (By now, [The lines of code here](https://github.com/GoogleCloudPlatform/cloudml-samples/blob/master/mnist/distributed/trainer/model.py#L176-L185) are dedicated for CloudML.) For example, CloudML also reads the signatures in model. Maybe CloudML can support more generic TensorFlow model, so that developers can make less effort in code adaption for CloudML and we will contribute more models to CloudML.

**Comment by bhupc** [comment]
Thanks for the suggestion. 
As joshgc replied, Cloud ML serving does have a signature concept.  For compatibility of SavedModel between Cloud ML and tensorflow model server, Yes, we are working towards that and we hope users can get some level of seamless experience there.

**Comment by ohmystack** [comment]
Thanks for @bhupc your replying. I'll close this PR now.

**Pull request closed without merging**
