### PR TITLE
fix INVALID_ARGUMENT error

### PR DESCRIPTION
**Pull request by eran-levy**
1. Trained a model
2. Export the model to deploy into cloud ML
3. Request online prediction: 
gcloud ml-engine predict --model model-name --json-instances model/request.json --version v3

Online prediction results with the following error:
NetworkError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'keras_learning_phase' with dtype uint8
     [[Node: keras_learning_phase = Placeholder[dtype=DT_UINT8, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]")

Reading the Keras blog: https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html#exporting-a-model-with-tensorflow-serving
and this issue discussion: https://github.com/keras-team/keras/issues/2310
Its necessary to set the set_learning_phase

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/141)

### CODE REVIEW

**Comment by eran-levy** [comment]
I signed it!

**Comment by eran-levy** [comment]
Hi @gogasca , Thanks, fixed. See last commit

**Comment by eran-levy** [comment]
@gogasca done, unified comments, see last commit

**Comment by gogasca** [comment]
Looks good now, There was a minor conflict, but is now merged. Thanks for contributing!

**Pull request merged**
