### PR TITLE
sklearn - adding notebook for serving PyTorch model using CMLE 

### PR DESCRIPTION
**Pull request by ksalama**
The notebook illustrates how to train a simple PyTorch model, and serve it to CMLE using the custom prediction code.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/261)

### CODE REVIEW

**Comment by ksalama** [comment]
@puneith - kindly review this notebook. Thanks

**Comment by puneith** [comment]
@ksalama awesome PR, thx much! Few comments:

- Can we make sure this notebook runs in CMLE using colab
- Iris is nice, but developers want something beyond Iris. Can we either modify this or add another notebook with a different use-case? @happyhuman may be that's something you can take up.

**Comment by ksalama** [comment]
@puneith - Thank you for your comments
- I run
 the notebook in colab, and added the necessary code to authenticate the user. I tested it end-to-end it works fine. Are there any other particulars that I need to consider?
- Sure, I can add another notebook for census and/or MNIST. However, I think objective is to demonstrate serving a PyTorch model, regardless the complexity of the model.

**Comment by puneith** [comment]
@ksalama please revert this PR. We should not put this under sklearn.

**Comment by ksalama** [comment]
@puneith - Thanks for this.

Which directory should this go to? Some suggestions

- cloudml-samples/other_frameworks

- cloudml-samples/other_frameworks/pytorch

- cloudml-samples/pytorch

It seems that there is an emphasis recently on the support of pytorch on GCP.  So I recommend the third, followed by the, second option.  I also would put the notebook in the same directory of the user guide notebook.

Please advise...

**Comment by puneith** [comment]
Option 3 makes sense. @nnegrey

**Comment by nnegrey** [comment]
`cloudml-samples/pytorch`
Would be perfect!
Thanks!

(I'm traveling this week, sorry if my review gets a little delayed)

**Pull request merged**
