### PR TITLE
Getting started in Keras tutorial notebook

### PR DESCRIPTION
**Pull request by alecglassford**
Made all the last changes that Crystal suggested, specifically: 
* made setup instructions as specific as possible for different environments
* added output cells

I've done some cleanup on the output cells to make them as generally applicable as possible:
* replaced my personal project and bucket names with `<your-project-id>` and `<your-bucket-name>` in the logs
* Made sure the cell execution numberings reads as a clear 1 through 39 (even though I didn't always run them in exactly in order/ran some cells more than once ☺️)

The log outputs for the training job take up a lot of space, but Colab and the local Jupyter environment add a scrollbar so it's not awful to work with, just perhaps annoying to look at in GitHub. It may be worth setting the trainer to run for fewer epochs (e.g. 5 instead of 20) just for convenience, but we can do this in future work.

---
This change is [Reviewable](https://reviewable.io/reviews/googlecloudplatform/cloudml-samples/387)

### CODE REVIEW

**Comment by alecglassford** [comment]
If you're having trouble previewing the notebook in the GitHub PR interface like I am, I believe [this rendered version](https://nbviewer.jupyter.org/github/GoogleCloudPlatform/cloudml-samples/blob/8a9996a26cf0e28483d476c3d403ce825d4ef32a/notebooks/tensorflow/getting-started-keras.ipynb) is similar to what the GitHub renderer does.

**Comment by alecglassford** [comment]
I'd be happy to remove output. It is useful for readers in some cases, but in many cases it's not. (And hopefully readers will run the cells themselves anyway.)

@thedriftofwords requested that we add it, so maybe she can share her thoughts.

I do think, for the notebook format at least, it makes the most sense to either show output for all the cells or don't show any at all. If we show output for some cells, I think that raises some confusion about how you're supposed to run the notebook. (E.g. Am I as a reader also supposed to skip around?) This differs for cloud.google.com, where I think it makes sense to selectively show output, since we're not posing that as a notebook.

**Comment by gogasca** [comment]
> I'd be happy to remove output. It is useful for readers in some cases, but in many cases it's not. (And hopefully readers will run the cells themselves anyway.)
> 
> @thedriftofwords requested that we add it, so maybe she can share her thoughts.
> 
> I do think, for the notebook format at least, it makes the most sense to either show output for all the cells or don't show any at all. If we show output for some cells, I think that raises some confusion about how you're supposed to run the notebook. (E.g. Am I as a reader also supposed to skip around?) This differs for cloud.google.com, where I think it makes sense to selectively show output, since we're not posing that as a notebook.

That's fine, i just that last cell has an error. Would be nice cleaning up last cell

**Comment by alecglassford** [comment]
OK, I'll  tweak that last job cancellation command.

**Comment by alecglassford** [comment]
Done: d76308c

**Pull request merged**
