### PR TITLE
Now needs TF v1.4

### PR DESCRIPTION
**Pull request by RemiTurpaud**
Updated the "Training using Cloud ML Engine" command example to use the version 1.4 of Tensor Flow, now used in this sample.

### CODE REVIEW

**Comment by RemiTurpaud** [comment]
signed

**Comment by puneith** [comment]
Can you please confirm that you ran the sample locally/cloud and it worked with 1.4?

**Comment by RemiTurpaud** [comment]
It ran fine on cloud. In fact, it doesn't run anymore with 1.2 (see last commit - 5b6b901).

**Comment by puneith** [comment]
Thanks for the PR.

**Pull request merged**
